spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/globber
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: "globberdpm"
    password: "raug eqng xmkn mivd"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            enable: true
        debug: true


  data:
    redis:
      repositories:
        enabled: false
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 4a397939d2fdf4b239db1a6b014c2cb5
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            client-secret: awndgGUTXtjVPP5xxqmftbezbZHUxNdc
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# http://localhost:8080/oauth2/authorization/kakao

logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: debug

jwt:
  secret: globberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobberglobber
  access_expiration: 864000
  refresh_expiration: 8640000

oauth2_redirect_uri:
  success: http://localhost:8080/login/oauth/success?accessToken=
  failure: http://localhost:8080/login/oauth/failure

server:
  port: 8080