name: 백엔드 CI

on:
  push:
    branches:
      - "develop"
      - "main"

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    permissions:
      contents: read

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SECRETS_SUBMODULE_ACCESS_TOKEN }}

      - name: JDK 21 설정
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: 프로젝트 클린 & 테스트 & 빌드
        run: |
          ./gradlew clean test build

      - name: Docker Hub 로그인
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시 (브랜치별 태깅)
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::7}

          if [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            docker buildx build -f Dockerfile.dev \
              --platform linux/arm64 \
              -t one/one:dev-$VERSION \
              -t one/one:dev-latest \
              --push .
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            docker buildx build -f Dockerfile \
              --platform linux/arm64 \
              -t one/one:prod-$VERSION \
              -t one/one:prod-latest \
              --push .
          fi
