name: 백엔드 CD (PROD)

on:
  workflow_run:
    workflows: ["백엔드 CI"]
    branches: [ "main" ]
    types:
      - completed

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, prod]

    steps:
      - name: 실행 중인 컨테이너 중지 및 삭제
        run: |
          docker stop prod || true && docker rm prod || true
          docker stop promtail_prod || true && docker rm promtail_prod || true

      - name: prod 네트워크 생성 확인
        run: docker network create prod_network || true

      - name: Docker Compose Pull & Up 실행
        run: |
          cd backend
          docker compose -f config/docker-compose-prod.yml pull
          docker compose -f config/docker-compose-prod.yml up -d

      - name: Docker 이미지 정리
        run: docker image prune -af
